apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.username | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.password | b64enc }}